# -*- coding: utf-8 -*-
"""worksheet1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19xMsTKRg0SdwSohO7LvAWs8zO3rUu2pj
"""

a=10

a + 20

type(a)

s = "sudh"

type(s)

b = 56.56

type(b)

s = "sudh"

type(s)

s1 ='sudhsfdsdf'

type(s1)

s = "fdf"

S="dsdfd"

s

s

int = 1

int

s% = "fsdfds"

s& = "fsdf"

type(s)

print(s)

s

b = true

b = True

b

b1 = False

b1

True + False

False - False

True * True

True/False

c = 7 + 6j

c = 7 + 6j

type(c)

c.real

c.imag

s = "sudh"

s

s  +3

s + "3"

s + str(3)

student = "neuron"

print(student)

